name: watch_store
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  carousel_slider: ^5.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/fonts/
    - assets/png/

  fonts:
    - family: dana
      fonts:
        - asset: assets/fonts/thin.ttf
          weight: 100
        - asset: assets/fonts/light.ttf
          weight: 200
        - asset: assets/fonts/extralight.ttf
          weight: 300
        - asset: assets/fonts/regular.ttf
          weight: 400
        - asset: assets/fonts/medium.ttf
          weight: 500
        - asset: assets/fonts/demibold.ttf
          weight: 600
        - asset: assets/fonts/bold.ttf
          weight: 700
        - asset: assets/fonts/extrabold.ttf
          weight: 800        
        - asset: assets/fonts/ultrabold.ttf
          weight: 900